### ISSUE TITLE
Question: Does it work without SMS app?

### ISSUE THREAD

**Issue by Fabian42** [tianma8023/XposedSmsCode#1]
Sorry to post this on the bug tracker, I can't find the correct place for this.

Does this module also copy codes to the clipboard if no SMS app is installed?
I usually don't receive SMS, so I only install Google messenger every few months when I need an activation code and then uninstall it again. If this module can copy the codes to clipboard even if no SMS app is installed, I could get rid of it for good.

**Comment by tianma8023** [comment]
@Fabian42 
Hi Fabian :)
Yeah，it's the suitable place for bug tracker.

After my test（Uninstall system SMS app and test whether this module can work or not） on my mobile phone (LineageOS 15.1 with default SMS app (package name is `com.android.messaging`) )，<b>it works well in this case. </b> It works well without SMS app in theory, however, since I am just a Independent-Developer without many Android devices under this circumstance, and <b>there should be more tests in this case.</b> So I can't  guarantee that this module can work on your device very well.  

So, why not have a try or test by yourself? 

I would appreciate it if you could have a test and tellme the result.  :) 👍

**Comment by Fabian42** [comment]
Sadly I can't, it's incompatible with my device. :(
I have a Sony XPeria Z1 compact that wasn't updated by Sony in a long time,
so I'm stuck with Android 4.3 for now.

**Comment by tianma8023** [comment]
@Fabian42 
Oh, it'a bad news, I'm so sorry. :(

This module is compatible since `Android 4.4`. It's my fault for missing this important information in `Xposed Repository` and `README`. I will add this information later.

**Comment by Fabian42** [comment]
Oh wow, I just found out that I have a Sony XPeria T, not a Sony XPeria Z1 Compact. After years of owning it! But the facts for this issue don't change: My phone is still incompatible with the mod and updates for it are officially discontinued.
