### ISSUE TITLE
2.0.1 Cannot  parse SMS Code

### ISSUE THREAD

**Issue by tuyennn** [tianma8023/XposedSmsCode#7]
### Precondition

- EdXposed
- Pie
- Oxygen OS
- XposedSmsCode 2.0.1

### How to replicate

- Keyword:

OTP cua * la|OTP cua the * la|

- Message:

OTP cua the 21312 la **7121312**

### Expect Result

- **7121312** should be copied to clipboard

### Actual Result 

- Cannot  parse SMS Code

### Note:
- This still working well on 1.7.0
- After upgrading this did not work anymore

**Comment by tianma8023** [comment]
@tuyennn 
OK,  the algorithm of parsing code is updated since version of 2.x. We choose the neareast possible code to the keyword as the SMS code finally.
Actually, I don't know the meaning of "OTP", "cua" and the " la" ...
So there is an another workaround, you can custom your own SMS code match rules like the below:
```text
Institution or company: OTP
SMS code Keyword: OTP
SMS code regular expression: (?<![0-9])[0-9]{7}(?![0-9])    (by quick choose)
```
Hope it can help you :)

**Comment by tianma8023** [comment]
@tuyennn 
In addtion, you may remove the keywords of `OTP cua * la|OTP cua the * la|`. It seems to be the incorrect regular expression keywords.

**Comment by tuyennn** [comment]
> 
> 
> @tuyennn
> In addtion, you may remove the keywords of `OTP cua * la|OTP cua the * la|`. It seems to be the incorrect regular expression keywords.

@tianma8023 It kinda like:
Code of phone number xxxxxx is 00000

on 00000 is what I want to take from message and xxxxxx is the number I want to by pass and consider it * as whatever it is, it doesn't mater

**Comment by tuyennn** [comment]
@tianma8023 Thanks for that, I got it working
